### ISSUE TITLE
How to use this send. PHP file

### ISSUE THREAD

**Issue by zlh119** [castaway2000/EthOS-Dashboard#1]
How to use this send. PHP file
Can you explain it in detail?

Thank you for your efforts.

**Comment by castaway2000** [comment]
I built this for a friend as a fun project so this file was provided to me by him. As I understand this file lives on the server and is built into EthOS you would simply replace your default send.php file with this one. I wrote in the docs that it lives as a cronjob so you would find or make the php file and then make a cronjob to act as your polling service

to find it you should run:
file / -name send.php

to set a new cron:
crontab -e

The php script is polling for data from the GPU. Each time the script is called it polls the data and sends a snapshot of it to the backend via the dashboard url paramiters. it is then stored it can be served upon the basic dashboard I made when you load the website.

This file is critical specifically to get all the details from the GPU and mining processes that EthOS has provided. Seeing as EthOS has a dashboard for the paid version this was in the free version and as I recall this send file should already exist on the operating system but i could be wrong.

**Comment by castaway2000** [comment]
updated the readme with this explanation.
